# Generated by Django 2.1.4 on 2019-02-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_ex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ex',
            name='vaild_code',
            field=models.CharField(max_length=6),
        ),
    ]
